mhset.Jewels = {
	"Steadfast Jwl 1": { "Slots": "o--",  "SlotCount": 1,  "Rarity": 4},
	"Standfast Jwl 1": { "Slots": "oo-",  "SlotCount": 2,  "Rarity": 5},
	"Paralysis Jwl 1": { "Slots": "o--",  "SlotCount": 1,  "Rarity": 4},
	"Paralysis Jwl 2": { "Slots": "oo-",  "SlotCount": 2,  "Rarity": 5},
	"Pep Jewel 1": { "Slots": "o--",  "SlotCount": 1,  "Rarity": 4},
	"Pep Jewel 2": { "Slots": "oo-",  "SlotCount": 2,  "Rarity": 5},
	"Antidote Jewel 1": { "Slots": "o--",  "SlotCount": 1,  "Rarity": 4},
	"Antidote Jewel 2": { "Slots": "oo-",  "SlotCount": 2,  "Rarity": 5},
	"Def Lock Jewel 1": { "Slots": "o--",  "SlotCount": 1,  "Rarity": 4},
	"Alarm Jewel 1": { "Slots": "o--",  "SlotCount": 1,  "Rarity": 4},
	"Tracker Jewel 1": { "Slots": "o--",  "SlotCount": 1,  "Rarity": 4},
	"Trekker Jewel 1": { "Slots": "o--",  "SlotCount": 1,  "Rarity": 4},
	"Staunch Jewel 1": { "Slots": "o--",  "SlotCount": 1,  "Rarity": 4},
	"Clean Jewel 1": { "Slots": "o--",  "SlotCount": 1,  "Rarity": 7},
	"Sane Jewel 1": { "Slots": "o--",  "SlotCount": 1,  "Rarity": 8},
	"Sane Jewel 3": { "Slots": "ooo",  "SlotCount": 3,  "Rarity": 8},
	"Footing Jewel 1": { "Slots": "o--",  "SlotCount": 1,  "Rarity": 4},
	"Tectonic Jewel 1": { "Slots": "o--",  "SlotCount": 1,  "Rarity": 4},
	"Heat Res Jewel 1": { "Slots": "o--",  "SlotCount": 1,  "Rarity": 4},
	"Cold Res Jewel 1": { "Slots": "o--",  "SlotCount": 1,  "Rarity": 4},
	"Earplug Jewel 1": { "Slots": "o--",  "SlotCount": 1,  "Rarity": 4},
	"Earplug Jewel 3": { "Slots": "ooo",  "SlotCount": 3,  "Rarity": 6},
	"Wind Res Jewel 1": { "Slots": "o--",  "SlotCount": 1,  "Rarity": 4},
	"Wind Res Jewel 2": { "Slots": "oo-",  "SlotCount": 2,  "Rarity": 5},
	"Attack Jewel 1": { "Slots": "o--",  "SlotCount": 1,  "Rarity": 4},
	"Attack Jewel 2": { "Slots": "oo-",  "SlotCount": 2,  "Rarity": 5},
	"Attack Jewel 3": { "Slots": "ooo",  "SlotCount": 3,  "Rarity": 6},
	"Expert Jewel 1": { "Slots": "o--",  "SlotCount": 1,  "Rarity": 4},
	"Expert Jewel 2": { "Slots": "oo-",  "SlotCount": 2,  "Rarity": 5},
	"Expert Jewel 3": { "Slots": "ooo",  "SlotCount": 3,  "Rarity": 6},
	"Disabler Jewel 1": { "Slots": "o--",  "SlotCount": 1,  "Rarity": 4},
	"Disabler Jewel 2": { "Slots": "oo-",  "SlotCount": 2,  "Rarity": 5},
	"Element Jewel 1": { "Slots": "o--",  "SlotCount": 1,  "Rarity": 4},
	"Element Jewel 3": { "Slots": "ooo",  "SlotCount": 3,  "Rarity": 6},
	"Blaze Jewel 1": { "Slots": "o--",  "SlotCount": 1,  "Rarity": 4},
	"Blaze Jewel 2": { "Slots": "oo-",  "SlotCount": 2,  "Rarity": 5},
	"Stream Jewel 1": { "Slots": "o--",  "SlotCount": 1,  "Rarity": 4},
	"Stream Jewel 2": { "Slots": "oo-",  "SlotCount": 2,  "Rarity": 5},
	"Bolt Jewel 1": { "Slots": "o--",  "SlotCount": 1,  "Rarity": 4},
	"Bolt Jewel 2": { "Slots": "oo-",  "SlotCount": 2,  "Rarity": 5},
	"Frost Jewel 1": { "Slots": "o--",  "SlotCount": 1,  "Rarity": 4},
	"Frost Jewel 2": { "Slots": "oo-",  "SlotCount": 2,  "Rarity": 5},
	"Dragon Jewel 1": { "Slots": "o--",  "SlotCount": 1,  "Rarity": 4},
	"Dragon Jewel 2": { "Slots": "oo-",  "SlotCount": 2,  "Rarity": 5},
	"Tenderizer Jwl 1": { "Slots": "o--",  "SlotCount": 1,  "Rarity": 4},
	"Tenderizer Jwl 3": { "Slots": "ooo",  "SlotCount": 3,  "Rarity": 6},
	"Destroyer Jwl 1": { "Slots": "o--",  "SlotCount": 1,  "Rarity": 4},
	"Destroyer Jwl 3": { "Slots": "ooo",  "SlotCount": 3,  "Rarity": 6},
	"CritElementJwl 1": { "Slots": "o--",  "SlotCount": 1,  "Rarity": 8},
	"CritElementJwl 2": { "Slots": "oo-",  "SlotCount": 2,  "Rarity": 9},
	"Crit Status Jwl 1": { "Slots": "o--",  "SlotCount": 1,  "Rarity": 8},
	"Crit Status Jwl 2": { "Slots": "oo-",  "SlotCount": 2,  "Rarity": 9},
	"Capacity Jewel 2": { "Slots": "oo-",  "SlotCount": 2,  "Rarity": 5},
	"Capacity Jewel 3": { "Slots": "ooo",  "SlotCount": 3,  "Rarity": 6},
	"Laden Jewel 3": { "Slots": "ooo",  "SlotCount": 3,  "Rarity": 8},
	"Charger Jewel 1": { "Slots": "o--",  "SlotCount": 1,  "Rarity": 4},
	"Charger Jewel 3": { "Slots": "ooo",  "SlotCount": 3,  "Rarity": 6},
	"Throttle Jewel 1": { "Slots": "o--",  "SlotCount": 1,  "Rarity": 4},
	"Throttle Jewel 2": { "Slots": "oo-",  "SlotCount": 2,  "Rarity": 5},
	"KO Jewel 1": { "Slots": "o--",  "SlotCount": 1,  "Rarity": 4},
	"KO Jewel 2": { "Slots": "oo-",  "SlotCount": 2,  "Rarity": 5},
	"Drain Jewel 1": { "Slots": "o--",  "SlotCount": 1,  "Rarity": 4},
	"Drain Jewel 2": { "Slots": "oo-",  "SlotCount": 2,  "Rarity": 5},
	"Potential Jwl 1": { "Slots": "o--",  "SlotCount": 1,  "Rarity": 4},
	"Potential Jwl 2": { "Slots": "oo-",  "SlotCount": 2,  "Rarity": 5},
	"Fortitude Jwl 1": { "Slots": "o--",  "SlotCount": 1,  "Rarity": 4},
	"Fortitude Jwl 2": { "Slots": "oo-",  "SlotCount": 2,  "Rarity": 5},
	"Bombardier Jwl 1": { "Slots": "o--",  "SlotCount": 1,  "Rarity": 4},
	"Sonorous Jewel 1": { "Slots": "o--",  "SlotCount": 1,  "Rarity": 4},
	"Artillery Jwl 1": { "Slots": "o--",  "SlotCount": 1,  "Rarity": 4},
	"Defense Jewel 1": { "Slots": "o--",  "SlotCount": 1,  "Rarity": 4},
	"Defense Jewel 2": { "Slots": "oo-",  "SlotCount": 2,  "Rarity": 5},
	"Defense Jewel 3": { "Slots": "ooo",  "SlotCount": 3,  "Rarity": 7},
	"Resistor Jewel 1": { "Slots": "o--",  "SlotCount": 1,  "Rarity": 4},
	"Resistor Jewel 3": { "Slots": "ooo",  "SlotCount": 3,  "Rarity": 6},
	"Fire Res Jewel 1": { "Slots": "o--",  "SlotCount": 1,  "Rarity": 4},
	"Nul-Fire Jewel 1": { "Slots": "o--",  "SlotCount": 1,  "Rarity": 4},
	"Water Res Jwl 1": { "Slots": "o--",  "SlotCount": 1,  "Rarity": 4},
	"Nul-Water Jwl 1": { "Slots": "o--",  "SlotCount": 1,  "Rarity": 4},
	"ThunderRes Jwl 1": { "Slots": "o--",  "SlotCount": 1,  "Rarity": 4},
	"Nul-Thundr Jwl 1": { "Slots": "o--",  "SlotCount": 1,  "Rarity": 4},
	"Ice Res Jewel 1": { "Slots": "o--",  "SlotCount": 1,  "Rarity": 4},
	"Nul-Ice Jewel 1": { "Slots": "o--",  "SlotCount": 1,  "Rarity": 4},
	"Dragon Res Jwl 1": { "Slots": "o--",  "SlotCount": 1,  "Rarity": 4},
	"Nul-Dragon Jwl 1": { "Slots": "o--",  "SlotCount": 1,  "Rarity": 4},
	"Protection Jwl 1": { "Slots": "o--",  "SlotCount": 1,  "Rarity": 4},
	"Asylum Jewel 1": { "Slots": "o--",  "SlotCount": 1,  "Rarity": 4},
	"Vitality Jewel 1": { "Slots": "o--",  "SlotCount": 1,  "Rarity": 4},
	"Recovery Jewel 1": { "Slots": "o--",  "SlotCount": 1,  "Rarity": 4},
	"Recovery Jewel 2": { "Slots": "oo-",  "SlotCount": 2,  "Rarity": 5},
	"Medicine Jewel 1": { "Slots": "o--",  "SlotCount": 1,  "Rarity": 4},
	"Medicine Jewel 2": { "Slots": "oo-",  "SlotCount": 2,  "Rarity": 5},
	"Evasion Jewel 1": { "Slots": "o--",  "SlotCount": 1,  "Rarity": 4},
	"Evasion Jewel 2": { "Slots": "oo-",  "SlotCount": 2,  "Rarity": 5},
	"Jumping Jewel 1": { "Slots": "o--",  "SlotCount": 1,  "Rarity": 4},
	"Jumping Jewel 2": { "Slots": "oo-",  "SlotCount": 2,  "Rarity": 8},
	"Sheath Jewel 1": { "Slots": "o--",  "SlotCount": 1,  "Rarity": 4},
	"Sheath Jewel 2": { "Slots": "oo-",  "SlotCount": 2,  "Rarity": 5},
	"Trapmaster Jwl 1": { "Slots": "o--",  "SlotCount": 1,  "Rarity": 4},
	"Gobbler Jewel 1": { "Slots": "o--",  "SlotCount": 1,  "Rarity": 4},
	"Gobbler Jewel 3": { "Slots": "ooo",  "SlotCount": 3,  "Rarity": 6},
	"Satiated Jewel 1": { "Slots": "o--",  "SlotCount": 1,  "Rarity": 7},
	"Sprinter Jewel 1": { "Slots": "o--",  "SlotCount": 1,  "Rarity": 4},
	"Sprinter Jewel 3": { "Slots": "ooo",  "SlotCount": 3,  "Rarity": 6},
	"Physique Jewel 1": { "Slots": "o--",  "SlotCount": 1,  "Rarity": 4},
	"Physique Jewel 2": { "Slots": "oo-",  "SlotCount": 2,  "Rarity": 5},
	"Refresh Jewel 1": { "Slots": "o--",  "SlotCount": 1,  "Rarity": 4},
	"Refresh Jewel 2": { "Slots": "oo-",  "SlotCount": 2,  "Rarity": 5},
	"Hungerless Jwl 1": { "Slots": "o--",  "SlotCount": 1,  "Rarity": 4},
	"Metabolism Jwl 1": { "Slots": "o--",  "SlotCount": 1,  "Rarity": 4},
	"Fate Jewel 1": { "Slots": "o--",  "SlotCount": 1,  "Rarity": 4},
	"Fate Jewel 3": { "Slots": "ooo",  "SlotCount": 3,  "Rarity": 6},
	"Capture Jewel 1": { "Slots": "o--",  "SlotCount": 1,  "Rarity": 4},
	"Capture Jewel 3": { "Slots": "ooo",  "SlotCount": 3,  "Rarity": 6},
	"Carver Jewel 1": { "Slots": "o--",  "SlotCount": 1,  "Rarity": 4},
	"Carver Jewel 3": { "Slots": "ooo",  "SlotCount": 3,  "Rarity": 6},
	"Transportr Jwl 1": { "Slots": "o--",  "SlotCount": 1,  "Rarity": 4},
	"Gathering Jwl 1": { "Slots": "o--",  "SlotCount": 1,  "Rarity": 4},
	"Spree Jewel 1": { "Slots": "o--",  "SlotCount": 1,  "Rarity": 4},
	"Blessing Jewel 1": { "Slots": "o--",  "SlotCount": 1,  "Rarity": 4},
	"Friendship Jwl 1": { "Slots": "o--",  "SlotCount": 1,  "Rarity": 4},
	"Friendship Jwl 2": { "Slots": "oo-",  "SlotCount": 2,  "Rarity": 5},
	"Psychic Jewel 1": { "Slots": "o--",  "SlotCount": 1,  "Rarity": 4},
	"Professor Jwl 1": { "Slots": "o--",  "SlotCount": 1,  "Rarity": 4},
	"Factory Jewel 1": { "Slots": "o--",  "SlotCount": 1,  "Rarity": 4},
	"Enduring Jewel 1": { "Slots": "o--",  "SlotCount": 1,  "Rarity": 4},
	"Perception Jwl 1": { "Slots": "o--",  "SlotCount": 1,  "Rarity": 4},
	"Ranger Jewel 1": { "Slots": "o--",  "SlotCount": 1,  "Rarity": 4},
	"Ninja Jewel 1": { "Slots": "o--",  "SlotCount": 1,  "Rarity": 5},
	"Handicraft Jwl 2": { "Slots": "oo-",  "SlotCount": 2,  "Rarity": 5},
	"Handicraft Jwl 3": { "Slots": "ooo",  "SlotCount": 3,  "Rarity": 6},
	"Artisan Jewel 3": { "Slots": "ooo",  "SlotCount": 3,  "Rarity": 8},
	"Fencer Jewel 1": { "Slots": "o--",  "SlotCount": 1,  "Rarity": 4},
	"Fencer Jewel 3": { "Slots": "ooo",  "SlotCount": 3,  "Rarity": 6},
	"Razor Jewel 1": { "Slots": "o--",  "SlotCount": 1,  "Rarity": 4},
	"Razor Jewel 3": { "Slots": "ooo",  "SlotCount": 3,  "Rarity": 6},
	"Draw Jewel 1": { "Slots": "o--",  "SlotCount": 1,  "Rarity": 4},
	"Draw Jewel 2": { "Slots": "oo-",  "SlotCount": 2,  "Rarity": 5},
	"Gambit Jewel 1": { "Slots": "o--",  "SlotCount": 1,  "Rarity": 4},
	"Gambit Jewel 3": { "Slots": "ooo",  "SlotCount": 3,  "Rarity": 6},
	"Ironwall Jewel 1": { "Slots": "o--",  "SlotCount": 1,  "Rarity": 4},
	"Ironwall Jewel 2": { "Slots": "oo-",  "SlotCount": 2,  "Rarity": 5},
	"Shield Jewel 1": { "Slots": "o--",  "SlotCount": 1,  "Rarity": 4},
	"Shield Jewel 2": { "Slots": "oo-",  "SlotCount": 2,  "Rarity": 5},
	"Grinder Jewel 1": { "Slots": "o--",  "SlotCount": 1,  "Rarity": 4},
	"Forceshot Jwl 1": { "Slots": "o--",  "SlotCount": 1,  "Rarity": 4},
	"Forceshot Jwl 3": { "Slots": "ooo",  "SlotCount": 3,  "Rarity": 6},
	"Pierce Jewel 1": { "Slots": "o--",  "SlotCount": 1,  "Rarity": 4},
	"Pierce Jewel 3": { "Slots": "ooo",  "SlotCount": 3,  "Rarity": 6},
	"Pellet Jewel 1": { "Slots": "o--",  "SlotCount": 1,  "Rarity": 4},
	"Pellet Jewel 3": { "Slots": "ooo",  "SlotCount": 3,  "Rarity": 6},
	"ShotPlus Jewel 1": { "Slots": "o--",  "SlotCount": 1,  "Rarity": 4},
	"ShotPlus Jewel 2": { "Slots": "oo-",  "SlotCount": 2,  "Rarity": 5},
	"PiercePlus Jwl 1": { "Slots": "o--",  "SlotCount": 1,  "Rarity": 4},
	"PelletPlus Jwl 1": { "Slots": "o--",  "SlotCount": 1,  "Rarity": 4},
	"CragPlus Jewel 1": { "Slots": "o--",  "SlotCount": 1,  "Rarity": 4},
	"ClustPlus Jwl 1": { "Slots": "o--",  "SlotCount": 1,  "Rarity": 4},
	"SlicePlus Jwl 1": { "Slots": "o--",  "SlotCount": 1,  "Rarity": 4},
	"BlastPlus Jwl 1": { "Slots": "o--",  "SlotCount": 1,  "Rarity": 4},
	"Salvo Jewel 1": { "Slots": "o--",  "SlotCount": 1,  "Rarity": 4},
	"Salvo Jewel 3": { "Slots": "ooo",  "SlotCount": 3,  "Rarity": 6},
	"Quickload Jwl 1": { "Slots": "o--",  "SlotCount": 1,  "Rarity": 4},
	"Quickload Jwl 2": { "Slots": "oo-",  "SlotCount": 2,  "Rarity": 5},
	"Absorber Jewel 1": { "Slots": "o--",  "SlotCount": 1,  "Rarity": 4},
	"Absorber Jewel 3": { "Slots": "ooo",  "SlotCount": 3,  "Rarity": 6},
	"Precise Jewel 1": { "Slots": "o--",  "SlotCount": 1,  "Rarity": 9},
	"Precise Jewel 2": { "Slots": "oo-",  "SlotCount": 2,  "Rarity": 9},
	"Sniper Jewel 1": { "Slots": "o--",  "SlotCount": 1,  "Rarity": 4},
	"Paracoat Jewel 1": { "Slots": "o--",  "SlotCount": 1,  "Rarity": 4},
	"Paracoat Jewel 2": { "Slots": "oo-",  "SlotCount": 2,  "Rarity": 5},
	"Sleepcoat Jwl 1": { "Slots": "o--",  "SlotCount": 1,  "Rarity": 4},
	"Poisoncoat Jwl 1": { "Slots": "o--",  "SlotCount": 1,  "Rarity": 4},
	"Powercoat Jwl 1": { "Slots": "o--",  "SlotCount": 1,  "Rarity": 4},
	"Powercoat Jwl 2": { "Slots": "oo-",  "SlotCount": 2,  "Rarity": 5},
	"Rangecoat Jwl 1": { "Slots": "o--",  "SlotCount": 1,  "Rarity": 4},
	"Blastcoat Jwl 1": { "Slots": "o--",  "SlotCount": 1,  "Rarity": 4},
	"Draincoat Jwl 1": { "Slots": "o--",  "SlotCount": 1,  "Rarity": 4},
	"Torchlight Jwl 1": { "Slots": "o--",  "SlotCount": 1,  "Rarity": 4},
	"Release Jewel 2": { "Slots": "oo-",  "SlotCount": 2,  "Rarity": 5},
	"Catalyst Jewel 3": { "Slots": "ooo",  "SlotCount": 3,  "Rarity": 6},
	"TrueCatalystJwl 3": { "Slots": "ooo",  "SlotCount": 3,  "Rarity": 8},
	"Guts Jewel 1": { "Slots": "o--",  "SlotCount": 1,  "Rarity": 4},
	"Guts Jewel 2": { "Slots": "oo-",  "SlotCount": 2,  "Rarity": 5},
	"Meateater Jwl 1": { "Slots": "o--",  "SlotCount": 1,  "Rarity": 4},
	"Meatlover Jwl 1": { "Slots": "o--",  "SlotCount": 1,  "Rarity": 4},
	"Fungiform Jewel 1": { "Slots": "o--",  "SlotCount": 1,  "Rarity": 7},
	"Honeybee Jewel 1": { "Slots": "o--",  "SlotCount": 1,  "Rarity": 4},
	"Queenbee Jewel 1": { "Slots": "o--",  "SlotCount": 1,  "Rarity": 4},
	"Biology Jewel 1": { "Slots": "o--",  "SlotCount": 1,  "Rarity": 4},
	"Microbio Jewel 1": { "Slots": "o--",  "SlotCount": 1,  "Rarity": 4},
	"Spirit Jewel 1": { "Slots": "o--",  "SlotCount": 1,  "Rarity": 4},
	"Spirit Jewel 2": { "Slots": "oo-",  "SlotCount": 2,  "Rarity": 5},
	"Flawless Jewel 1": { "Slots": "o--",  "SlotCount": 1,  "Rarity": 4},
	"Flawless Jewel 2": { "Slots": "oo-",  "SlotCount": 2,  "Rarity": 5},
	"Steady Jewel 1": { "Slots": "o--",  "SlotCount": 1,  "Rarity": 4},
	"Steady Jewel 3": { "Slots": "oo-",  "SlotCount": 2,  "Rarity": 5},
	"Player Jewel 1": { "Slots": "o--",  "SlotCount": 1,  "Rarity": 4},
	"Morale Jewel 1": { "Slots": "o--",  "SlotCount": 1,  "Rarity": 4},
	"Leader Jewel 1": { "Slots": "o--",  "SlotCount": 1,  "Rarity": 4},
	"Leader Jewel 2": { "Slots": "oo-",  "SlotCount": 2,  "Rarity": 5},
	"Charmer Jewel 1": { "Slots": "o--",  "SlotCount": 1,  "Rarity": 4},
	"Rodeo Jewel 1": { "Slots": "o--",  "SlotCount": 1,  "Rarity": 7},
	"Honed Jwl 1": { "Slots": "o--",  "SlotCount": 1,  "Rarity": 4},
	"Honed Jwl 2": { "Slots": "oo-",  "SlotCount": 2,  "Rarity": 5},
	"Honed Jwl 3": { "Slots": "ooo",  "SlotCount": 3,  "Rarity": 6},
	"True Honed Jwl 2": { "Slots": "oo-",  "SlotCount": 2,  "Rarity": 6},
	"True Honed Jwl 3": { "Slots": "ooo",  "SlotCount": 3,  "Rarity": 7},
	"UltimateHonedJwl3": { "Slots": "ooo",  "SlotCount": 3,  "Rarity": 8},
	"Cutting Jwl 1": { "Slots": "o--",  "SlotCount": 1,  "Rarity": 4},
	"Cutting Jwl 2": { "Slots": "oo-",  "SlotCount": 2,  "Rarity": 5},
	"Cutting Jwl 3": { "Slots": "ooo",  "SlotCount": 3,  "Rarity": 6},
	"TrueCuttingJwl 3": { "Slots": "ooo",  "SlotCount": 3,  "Rarity": 7},
	"Calm Jwl 1": { "Slots": "o--",  "SlotCount": 1,  "Rarity": 4},
	"Calm Jwl 2": { "Slots": "oo-",  "SlotCount": 2,  "Rarity": 5},
	"Calm Jwl 3": { "Slots": "ooo",  "SlotCount": 3,  "Rarity": 6},
	"True Calm Jwl 2": { "Slots": "oo-",  "SlotCount": 2,  "Rarity": 6},
	"True Calm Jwl 3": { "Slots": "ooo",  "SlotCount": 3,  "Rarity": 7},
	"UltimateCalmJwl 3": { "Slots": "ooo",  "SlotCount": 3,  "Rarity": 8},
	"Hale Jwl 1": { "Slots": "o--",  "SlotCount": 1,  "Rarity": 4},
	"Hale Jwl 2": { "Slots": "oo-",  "SlotCount": 2,  "Rarity": 5},
	"Hale Jwl 3": { "Slots": "ooo",  "SlotCount": 3,  "Rarity": 6},
	"True Hale Jwl 2": { "Slots": "oo-",  "SlotCount": 3,  "Rarity": 6},
	"True Hale Jwl 3": { "Slots": "ooo",  "SlotCount": 3,  "Rarity": 7},
	"UltimateHaleJwl 3": { "Slots": "ooo",  "SlotCount": 3,  "Rarity": 8},
	"Ire Jwl 1": { "Slots": "o--",  "SlotCount": 1,  "Rarity": 4},
	"Ire Jwl 2": { "Slots": "oo-",  "SlotCount": 2,  "Rarity": 5},
	"Ire Jwl 3": { "Slots": "ooo",  "SlotCount": 3,  "Rarity": 6},
	"True Ire Jwl 2": { "Slots": "oo-",  "SlotCount": 3,  "Rarity": 6},
	"True Ire Jwl 3": { "Slots": "ooo",  "SlotCount": 3,  "Rarity": 7},
	"UltimateIreJwl 3": { "Slots": "ooo",  "SlotCount": 3,  "Rarity": 8},
	"Nimble Jwl 1": { "Slots": "o--",  "SlotCount": 1,  "Rarity": 4},
	"True Nimble Jwl 1": { "Slots": "o--",  "SlotCount": 1,  "Rarity": 5},
	"Nimble Jwl 2": { "Slots": "oo-",  "SlotCount": 2,  "Rarity": 5},
	"Nimble Jwl 3": { "Slots": "ooo",  "SlotCount": 3,  "Rarity": 6},
	"True Nimble Jwl 3": { "Slots": "ooo",  "SlotCount": 3,  "Rarity": 7},
	"Hardy Jwl 1": { "Slots": "o--",  "SlotCount": 1,  "Rarity": 4},
	"True Hardy Jwl 1": { "Slots": "o--",  "SlotCount": 1,  "Rarity": 5},
	"Hardy Jwl 2": { "Slots": "oo-",  "SlotCount": 2,  "Rarity": 5},
	"Hardy Jwl 3": { "Slots": "ooo",  "SlotCount": 3,  "Rarity": 6},
	"True Hardy Jwl 3": { "Slots": "ooo",  "SlotCount": 3,  "Rarity": 7},
	"Furtive Jwl 1": { "Slots": "o--",  "SlotCount": 1,  "Rarity": 4},
	"Furtive Jwl 2": { "Slots": "oo-",  "SlotCount": 2,  "Rarity": 5},
	"Furtive Jwl 3": { "Slots": "ooo",  "SlotCount": 3,  "Rarity": 6},
	"TrueFurtiveJwl 3": { "Slots": "ooo",  "SlotCount": 3,  "Rarity": 7},
	"Withdrawn Jwl 1": { "Slots": "o--",  "SlotCount": 1,  "Rarity": 4},
	"Withdrawn Jwl 2": { "Slots": "oo-",  "SlotCount": 2,  "Rarity": 5},
	"Withdrawn Jwl 3": { "Slots": "ooo",  "SlotCount": 3,  "Rarity": 6},
	"TrueWithdrawnJwl3": { "Slots": "ooo",  "SlotCount": 3,  "Rarity": 7},
	"Arcane Jwl 1": { "Slots": "o--",  "SlotCount": 1,  "Rarity": 4},
	"Arcane Jwl 2": { "Slots": "oo-",  "SlotCount": 2,  "Rarity": 5},
	"Arcane Jwl 3": { "Slots": "ooo",  "SlotCount": 3,  "Rarity": 6},
	"True Arcane Jwl 3": { "Slots": "ooo",  "SlotCount": 3,  "Rarity": 7},
	"Brawn Jwl 1": { "Slots": "o--",  "SlotCount": 1,  "Rarity": 4},
	"Brawn Jwl 2": { "Slots": "oo-",  "SlotCount": 2,  "Rarity": 5},
	"Brawn Jwl 3": { "Slots": "ooo",  "SlotCount": 3,  "Rarity": 6},
	"True Brawn Jwl 3": { "Slots": "ooo",  "SlotCount": 3,  "Rarity": 7},
	"Impactful Jwl 1": { "Slots": "o--",  "SlotCount": 1,  "Rarity": 4},
	"Impactful Jwl 2": { "Slots": "oo-",  "SlotCount": 2,  "Rarity": 5},
	"Impactful Jwl 3": { "Slots": "ooo",  "SlotCount": 3,  "Rarity": 6},
	"TrueImpactfulJwl3": { "Slots": "ooo",  "SlotCount": 3,  "Rarity": 7},
	"Intense Jwl 2": { "Slots": "oo-",  "SlotCount": 2,  "Rarity": 5},
	"Intense Jwl 3": { "Slots": "ooo",  "SlotCount": 3,  "Rarity": 6},
	"TrueIntenseJwl 2": { "Slots": "oo-",  "SlotCount": 2,  "Rarity": 6},
	"TrueIntenseJwl 3": { "Slots": "ooo",  "SlotCount": 3,  "Rarity": 7},
	"Aegis Jwl 2": { "Slots": "oo-",  "SlotCount": 2,  "Rarity": 5},
	"Aegis Jwl 3": { "Slots": "ooo",  "SlotCount": 3,  "Rarity": 6},
	"True Aegis Jwl 2": { "Slots": "oo-",  "SlotCount": 2,  "Rarity": 6},
	"True Aegis Jwl 3": { "Slots": "ooo",  "SlotCount": 3,  "Rarity": 7},
	"Tactful Jwl 2": { "Slots": "oo-",  "SlotCount": 2,  "Rarity": 5},
	"Tactful Jwl 3": { "Slots": "ooo",  "SlotCount": 3,  "Rarity": 6},
	"TrueTactfulJwl 2": { "Slots": "oo-",  "SlotCount": 2,  "Rarity": 6},
	"TrueTactfulJwl 3": { "Slots": "ooo",  "SlotCount": 3,  "Rarity": 7},
	"Broad Jwl 2": { "Slots": "oo-",  "SlotCount": 2,  "Rarity": 5},
	"Broad Jwl 3": { "Slots": "ooo",  "SlotCount": 3,  "Rarity": 6},
	"True Broad Jwl 2": { "Slots": "oo-",  "SlotCount": 2,  "Rarity": 6},
	"True Broad Jwl 3": { "Slots": "ooo",  "SlotCount": 3,  "Rarity": 7},
	"Supplicant Jwl 1": { "Slots": "o--",  "SlotCount": 1,  "Rarity": 4},
	"Supplicant Jwl 2": { "Slots": "oo-",  "SlotCount": 2,  "Rarity": 5},
	"Supplicant Jwl 3": { "Slots": "ooo",  "SlotCount": 3,  "Rarity": 6},
	"Trove Jwl 1": { "Slots": "o--",  "SlotCount": 1,  "Rarity": 4},
	"True Trove Jwl 1": { "Slots": "o--",  "SlotCount": 1,  "Rarity": 4},
	"Trove Jwl 2": { "Slots": "oo-",  "SlotCount": 2,  "Rarity": 5},
	"True Trove Jwl 2": { "Slots": "oo-",  "SlotCount": 2,  "Rarity": 6},
	"Trove Jwl 3": { "Slots": "ooo",  "SlotCount": 3,  "Rarity": 6},
	"Avid Jwl 1": { "Slots": "o--",  "SlotCount": 1,  "Rarity": 4},
	"Avid Jwl 2": { "Slots": "oo-",  "SlotCount": 2,  "Rarity": 5},
	"Avid Jwl 3": { "Slots": "ooo",  "SlotCount": 3,  "Rarity": 6},
	"True Avid Jwl 1": { "Slots": "o--",  "SlotCount": 1,  "Rarity": 5},
	"True Avid Jwl 2": { "Slots": "oo-",  "SlotCount": 2,  "Rarity": 6}
}
